site_name: My Docs
plugins:
  - search
theme:
  name: material
  features:
      - navigation.footer
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.tracking
      - navigation.top
      - search.suggest
      - search.highlight
      - content.code.annotate
      - content.code.copy
      - content.tooltips
  palette:
        # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
nav:
- Home: 'index.md'
- Set Up:
    - 'Preferences': 
        - 'Review': 'configuration/preferences/review.md'
        - 'Section 1: FreeAPS X': 'configuration/preferences/freeapsx.md'
        - 'Section 2: Statistics': 'configuration/preferences/statistics.md'
        - 'Section 3: Main Settings': 'configuration/preferences/mainsettings.md'
        - 'Section 4: Dynamic Settings': 'configuration/preferences/dynamicsettings.md'
        - 'Section 5: SMB Settings': 'configuration/preferences/smbsettings.md'
        - 'Section 6: Target Settings': 'configuration/preferences/targetsettings.md'
        - 'Section 7: Other Settings': 'configuration/preferences/othersettings.md'
    - 'Features':
        - 'Autobolus': 'configuration/concepts/smb-uam.md'
        - 'Autotune': 'configuration/concepts/autotune.md'
        - 'Auto-sensitivity': 'configuration/concepts/autosens-dynamic.md'
