site_name: FreeAPS X Docs
plugins:
  - search
theme:
  name: material
  features:
      - navigation.footer
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.tracking
      - navigation.top
      - search.suggest
      - search.highlight
      - content.code.annotate
      - content.code.copy
      - content.tooltips
  logo: logo.png
  favicon: logo.png
  palette:
        # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
nav:
- Home: 'index.md'
- Intro:
    - 'Requirements':
        - 'Compatible Mac': 'intro/requirements/mac.md'
        - 'Compatible iPhone': 'intro/requirements/iphone.md'
        - 'Compatible CGM': 'intro/requirements/cgm.md'
        - 'Compatible Pump': 'intro/requirements/pump.md'
    - 'Installing':
        - 'Testflight': 'intro/installing/testflight.md'
        - 'Building': 'intro/installing/building.md'

- Set Up:
    - 'Devices':
        - 'CGM': 'settings/devices/cgm.md'
        - 'Pump': 'settings/devices/pump.md'

    - 'Services':
        - 'Apple Health': 'settings/services/applehealth.md'
        - 'Nightscout': 'settings/services/nightscout.md'
        - 'Notifications': 'settings/services/notifications.md'

    - 'Configuration':
        - 'Preferences': 
            - 'Review': 'settings/configuration/preferences/review.md'
            - 'Section 1: FreeAPS X': 'settings/configuration/preferences/freeapsx.md'
            - 'Section 2: Statistics': 'settings/configuration/preferences/statistics.md'
            - 'Section 3: Main Settings': 'settings/configuration/preferences/mainsettings.md'
            - 'Section 4: Dynamic Settings': 'settings/configuration/preferences/dynamicsettings.md'
            - 'Section 5: SMB Settings': 'settings/configuration/preferences/smbsettings.md'
            - 'Section 6: Target Settings': 'settings/configuration/preferences/targetsettings.md'
            - 'Section 7: Other Settings': 'settings/configuration/preferences/othersettings.md'
            - 'Concepts':
                - 'Basal, ISF, ICR': 'settings/configuration/concepts/basal-isf-icr.md'
                - 'Autobolus': 'settings/configuration/concepts/smb-uam.md'
                - 'Autotune': 'settings/configuration/concepts/autotune.md'
                - 'Auto-sensitivity': 'settings/configuration/concepts/autosens-dynamic.md'
        - 'Pump Settings': 'settings/configuration/pumpsettings.md'
        - 'Basal Profile': 'settings/configuration/basalprofile.md'
        - 'Insulin Sensitivities': 'settings/configuration/insulinsensitivites.md'
        - 'Carb Ratios': 'settings/configuration/carbratios.md'
        - 'Target Ranges': 'settings/configuration/targetranges.md'
        - 'Autotune': 'settings/configuration/autotune.md'

# Troubleshooting and optimizing settings
- Troubleshoot: 
    - 'Debug': "troubleshoot/debug.md"
    - 'Logs': "troubleshoot/logs.md"

- Resources:
    - 'Resources': 'resources/resources.md'

  
