site_name: FreeAPS X Docs
theme:
  name: material
  features:
      - navigation.footer
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.tracking
      - navigation.top
      - search.suggest
      - search.highlight
      - content.code.annotate
      - content.code.copy
      - content.tooltips
  logo: logo.png
  favicon: logo.png
  palette:
        # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

markdown_extensions:
    - meta
    - abbr
    - admonition
    - attr_list
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences:
        # make exceptions to highlighting of code:
        custom_fences:
          - name:  mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.snippets:
        auto_append:
            - includes/tooltip-list.txt
    - toc:
        permalink: true
        permalink_title: Anchor link to this Header on this Page
        toc_depth: 3
        title: Headers on this Page
extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search

nav:
- Home: 'index.md'

- Intro: # Theses are taken from loop docs currently and need to be adapted; need to add macro to include docs for build options
    - 'Requirements':
        - 'Compatible iPhone': 'intro/requirements/iphone.md'
        - 'Compatible CGM': 'intro/requirements/cgm.md'
        - 'Compatible Pump': 'intro/requirements/pump.md'
        - 'RileyLink': 'intro/rileylink.md'
    - 'Installing':
        - 'Apple Developer Program': 'intro/installing/appledeveloper.md'
        - 'Compatible Mac': 'intro/installing/macbuild/computer.md'
        - 'Download Xcode': 'intro/installing/macbuild/xcode.md'
        - 'Xcode Preferences': 'intro/installing/macbuild/xcodepref.md'
        - 'Building': 'intro/installing/macbuild/buildpaid.md'
        - 'Build Free': 'intro/installing/macbuild/buildfree.md'
        - 'Testflight': 'intro/installing/macbuild/buildtestflight.md'
        
- Set Up:
    - 'Devices':
        - 'CGM': 'settings/devices/cgm.md'
        - 'Pump': 'settings/devices/pump.md'

    - 'Services':
        - 'Apple Health': 'settings/services/applehealth.md'
        - 'Nightscout': 'settings/services/nightscout.md'
        - 'Notifications': 'settings/services/notifications.md'

    - 'Configuration':
        - 'Preferences': 
            - 'Review': 'settings/configuration/preferences/review.md'
            - 'Section 1: FreeAPS X': 'settings/configuration/preferences/freeapsx.md'
            - 'Section 2: Statistics': 'settings/configuration/preferences/statistics.md'
            - 'Section 3: Main Settings': 'settings/configuration/preferences/mainsettings.md'
            - 'Section 4: Dynamic Settings': 'settings/configuration/preferences/dynamicsettings.md'
            - 'Section 5: SMB Settings': 'settings/configuration/preferences/smbsettings.md'
            - 'Section 6: Target Settings': 'settings/configuration/preferences/targetsettings.md'
            - 'Section 7: Other Settings': 'settings/configuration/preferences/othersettings.md'
            - 'Concepts':
                - 'Basal, ISF, ICR': 'settings/configuration/concepts/basal-isf-icr.md'
                - 'Autobolus': 'settings/configuration/concepts/smb-uam.md'
                - 'Autotune': 'settings/configuration/concepts/autotune.md'
                - 'Auto-sensitivity': 'settings/configuration/concepts/autosens-dynamic.md'
        - 'Pump Settings': 'settings/configuration/pumpsettings.md'
        - 'Basal Profile': 'settings/configuration/basalprofile.md'
        - 'Insulin Sensitivities': 'settings/configuration/insulinsensitivites.md'
        - 'Carb Ratios': 'settings/configuration/carbratios.md'
        - 'Target Ranges': 'settings/configuration/targetranges.md'
        - 'Autotune': 'settings/configuration/autotune.md'
    - 'Test Settings': 'settings/configuration/test.md'

# Troubleshooting and optimizing settings
- Troubleshoot: 
    - 'Build Errors': "troubleshoot/builderror.md" # Adapt from loopdocs
    - 'Debug': "troubleshoot/debug.md"
    - 'Logs': "troubleshoot/logs.md"

- Resources:
    - 'Citations': 'resources/citations.md'
    - 'BC Diabetes Agreement': 'resources/bcdiabetesagreement.md'

  
